import type { TerrainParams, TerrainPreset } from '../types/terrain';

export const DEFAULT_TERRAIN_PARAMS: TerrainParams = {
  seed: 'terrain-forge',
  width: 512,
  depth: 512,
  resolution: 129,
  maxHeight: 120,
  noiseScale: 175,
  octaves: 5,
  persistence: 0.48,
  lacunarity: 2.05,
  smoothing: 0.28,
  mountainIntensity: 1.0,
  hillIntensity: 0.72,
  erosion: 0.25,
  plainLevel: 0.22,
  valleyStrength: 0.48,
  randomness: 0.35,
  edgeFalloff: false,
  heightColors: true,
  verticalExaggeration: 1,
};

export const TERRAIN_PRESETS: TerrainPreset[] = [
  {
    id: 'soft-hills',
    name: 'Morros suaves',
    params: {
      ...DEFAULT_TERRAIN_PARAMS,
      seed: 'morros-suaves',
      width: 420,
      depth: 420,
      resolution: 129,
      maxHeight: 42,
      noiseScale: 210,
      octaves: 4,
      smoothing: 0.52,
      mountainIntensity: 0.18,
      hillIntensity: 1.15,
      erosion: 0.18,
      plainLevel: 0.45,
      valleyStrength: 0.2,
      randomness: 0.18,
    },
  },
  {
    id: 'serra-mineira',
    name: 'Serra mineira',
    params: {
      ...DEFAULT_TERRAIN_PARAMS,
      seed: 'serra-mineira',
      width: 620,
      depth: 460,
      resolution: 257,
      maxHeight: 135,
      noiseScale: 155,
      octaves: 6,
      persistence: 0.5,
      lacunarity: 2.12,
      smoothing: 0.22,
      mountainIntensity: 1.18,
      hillIntensity: 0.82,
      erosion: 0.35,
      plainLevel: 0.24,
      valleyStrength: 0.58,
      randomness: 0.38,
    },
  },
  {
    id: 'high-mountains',
    name: 'Montanhas altas',
    params: {
      ...DEFAULT_TERRAIN_PARAMS,
      seed: 'montanhas-altas',
      width: 640,
      depth: 640,
      resolution: 257,
      maxHeight: 240,
      noiseScale: 145,
      octaves: 7,
      persistence: 0.52,
      lacunarity: 2.18,
      smoothing: 0.16,
      mountainIntensity: 1.86,
      hillIntensity: 0.45,
      erosion: 0.32,
      plainLevel: 0.08,
      valleyStrength: 0.68,
      randomness: 0.42,
    },
  },
  {
    id: 'deep-valley',
    name: 'Vale profundo',
    params: {
      ...DEFAULT_TERRAIN_PARAMS,
      seed: 'vale-profundo',
      width: 700,
      depth: 520,
      resolution: 257,
      maxHeight: 170,
      noiseScale: 190,
      octaves: 6,
      persistence: 0.46,
      lacunarity: 2.05,
      smoothing: 0.2,
      mountainIntensity: 1.05,
      hillIntensity: 0.62,
      erosion: 0.46,
      plainLevel: 0.14,
      valleyStrength: 1.25,
      randomness: 0.32,
    },
  },
  {
    id: 'mountain-island',
    name: 'Ilha montanhosa',
    params: {
      ...DEFAULT_TERRAIN_PARAMS,
      seed: 'ilha-montanhosa',
      width: 520,
      depth: 520,
      resolution: 257,
      maxHeight: 150,
      noiseScale: 150,
      octaves: 6,
      smoothing: 0.24,
      mountainIntensity: 1.38,
      hillIntensity: 0.66,
      erosion: 0.3,
      plainLevel: 0.12,
      valleyStrength: 0.52,
      randomness: 0.34,
      edgeFalloff: true,
    },
  },
  {
    id: 'mobile-game',
    name: 'Terreno para jogo mobile',
    params: {
      ...DEFAULT_TERRAIN_PARAMS,
      seed: 'mobile-terrain',
      width: 320,
      depth: 320,
      resolution: 129,
      maxHeight: 70,
      noiseScale: 160,
      octaves: 4,
      smoothing: 0.38,
      mountainIntensity: 0.72,
      hillIntensity: 0.78,
      erosion: 0.2,
      plainLevel: 0.28,
      valleyStrength: 0.34,
      randomness: 0.2,
    },
  },
  {
    id: 'pc-realistic',
    name: 'Terreno realista para PC',
    params: {
      ...DEFAULT_TERRAIN_PARAMS,
      seed: 'pc-realista',
      width: 900,
      depth: 900,
      resolution: 257,
      maxHeight: 185,
      noiseScale: 235,
      octaves: 7,
      persistence: 0.49,
      lacunarity: 2.08,
      smoothing: 0.18,
      mountainIntensity: 1.28,
      hillIntensity: 0.7,
      erosion: 0.48,
      plainLevel: 0.18,
      valleyStrength: 0.76,
      randomness: 0.34,
    },
  },
];
